### ISSUE TITLE
That some of the files seem suspicious

### ISSUE THREAD

**Issue by ghost** [blastentwice/CK3-Family-Tree-Exporter-To-Gramps#1]
Try to download one of the things that is needed and it didn't do anything which is kind of a big red flag

**Comment by blastentwice** [comment]
Which files are you talking about? If it's rakaly or jq they are meant to just stay in your folder. The ck3gramps file itself will utilize them to produce the json from your save. Individually they are command line tools, which normally does nothing if double clicked but requires you to open the command prompt to use.
